DROP TABLE IF EXISTS users, items, bookings, requests, comments;

CREATE TABLE IF NOT EXISTS users
(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
email varchar(255) NOT NULL,
name varchar(512) NOT NULL,
CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(512) NOT NULL,
description varchar(1000) NOT NULL,
is_available boolean NOT NULL,
owner_id BIGINT,
request_id BIGINT,
CONSTRAINT user_items FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
start_date TIMESTAMP WITHOUT TIME ZONE,
end_date TIMESTAMP WITHOUT TIME ZONE,
item_id BIGINT,
booker_id BIGINT,
status varchar(50),
CONSTRAINT item_booking FOREIGN KEY (item_id) REFERENCES items (id),
CONSTRAINT user_booking FOREIGN KEY (booker_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests
(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
description varchar(1000) NOT NULL,
requestor_id BIGINT,
CONSTRAINT user_request FOREIGN KEY (requestor_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
text varchar(2000) NOT NULL,
item_id BIGINT,
author_id BIGINT,
CONSTRAINT user_comment FOREIGN KEY (author_id) REFERENCES users (id),
CONSTRAINT item_comment FOREIGN KEY (item_id) REFERENCES items (id)
);

ALTER TABLE items ADD FOREIGN KEY (request_id) REFERENCES requests (id)